#Getting this image ubuntu
#FROM scratch ( build empty image)

FROM ubuntu

MAINTAINER santhosh <vsantosh8602@gmail.com>

RUN apt-get update

CMD ["echo", "Hello World...! from my first docker image"]


